sonar.projectKey=vr1306_taskflow-fe
sonar.organization=vr1306
sonar.projectName=TaskFlow Frontend
sonar.projectVersion=1.0.0

# Source Code Configuration
sonar.sources=src
sonar.exclusions=**/*.test.*,**/*.spec.*,node_modules/**,.next/**,build/**,out/**,coverage/**,public/**

# Test Code Configuration
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/*.spec.tsx,**/*.spec.ts

# Encoding & Environment
sonar.sourceEncoding=UTF-8
sonar.javascript.environments=browser,node
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# SonarCloud Endpoint
sonar.host.url=https://sonarcloud.io
